# base_local_planner configuration, which is responsible for computing
# velocity commands to send to the base controller given a high-level
# plan.

TrajectoryPlannerROS:
  min_vel_x: 0.05
  max_vel_x: 0.05
  max_vel_y: 0.05

  max_vel_theta: 0.05
  min_in_place_val_theta: 0.005

  acc_lim_theta: 0.01
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2

  # We are not a holonomic robot, instead we are differential drive. Our robot has no way to "strafe"

  # Debug only disable
  visualize_potential: true

  holonomic_robot: false
