# Local cost-map configuration parameters.

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5

  # Visualization information frequency.
  publish_frequency: 2.0
  static_map: false

  # `true` here means the map stays centered around the robot. Might
  # impact reliability one way or the other; not sure, though.
  rolling_window: true

  # In meters.
  width: 6.0
  height: 6.0

  # Should probably be the same as the resolution of the static map.
  resolution: 0.05
