<robot name="david" xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <!-- Base Properties -->
  <xacro:property name="base_link_x" value="0.28" />
  <xacro:property name="base_link_y" value="0.18" />
  <xacro:property name="base_link_z" value="0" />

  <xacro:macro name="origin_rel" params="xraw yraw zraw rx ry rz">
  <origin  xyz="${ -base_link_x + xraw } ${ -base_link_y + yraw } ${ -base_link_z + zraw }" rpy="${ rx } ${ ry } ${ rz }" />
  </xacro:macro>
  <!-- Basic setup -->
  <link name="base_link" />
  <link name="laser" />
  <!-- Dump motors -->
  <!-- <link name="DUL_motor" /> -->
  <!-- <link name="DUL_block" /> -->
  <!-- <link name="DUR_motor" /> -->
  <!-- <link name="DUR_block" /> -->
  <!-- <!-\- Depth motors -\-> -->
  <!-- <link name="DEL_motor" /> -->
  <!-- <link name="DEL_block" /> -->
  <!-- <link name="DER_motor" /> -->
  <!-- <link name="DER_block" /> -->
  <!-- Pitch components -->
  <xacro:property name="pitch_pivot_attachment_length" value="0.37" />
  <xacro:property name="min_pitch_length" value="0.36" />
  <xacro:property name="pitch_pivot_attachment_length" value="0.37" />
  <!-- <link name="left_pitch_hinge" /> -->
  <!-- <link name="right_pitch_hinge" /> -->
  <!-- <link name="right_rear_pitch_pivot" /> -->
  <!-- <link name="left_rear_pitch_pivot" /> -->
  <!-- Auger components -->
  <xacro:property name="auger_length" value="0.71" />
  <!-- <link name="depth_motor_axle" /> -->
  <!-- <link name="auger_tip" /> -->
  <!-- <link name="auger_hole"/> -->

  <!-- Locomotion component -->
  <link name="left_loco_axle" />
  <link name="right_loco_axle" />


  <!-- Joints -->
  <joint name="base2laser" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="laser" />
    <axis xyz="0 0 0"/>
  </joint>

  <!-- Locomotion joints -->
  <joint name="loco_right" type="continuous">
    <parent link="base_link" />
    <child link="right_loco_axle"/>
    <xacro:origin_rel xraw="-0.065" yraw="-0.09" zraw="0.07" rx="0" ry="0" rz="0" />
    <axis xyz="0 0 0" />
  </joint>

  <joint name="loco_left" type="continuous">
    <parent link="base_link" />
    <child link="left_loco_axle"/>
    <xacro:origin_rel xraw="-0.065" yraw="0.09" zraw="0.07" rx="0" ry="0" rz="0" />
    <axis xyz="0 0 0" />
  </joint>
</robot>
